version: '3.2'

services:
  terraform-api:
    image: "gregoryguillou/terraform-api:${VERSION:-v0.1.9}"
    ports:
      - 10010:10010
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - $PWD/../../api/config/settings.yaml:/app/config/settings.yaml
    depends_on:
      - consul
      - couchbase
    restart: "always"

  runtime:
    image: "gregoryguillou/terraform-api:v0.1.9-runtime"
    depends_on:
      - consul
    environment:
      CONSUL_IP: consul
      GITHUB_REPOSITORY: "https://github.com/gregoryguillou/terraform-stacks.git"
    command: ["-c", "sleep 10"]
    entrypoint: ["/bin/bash"]
    restart: "no"

  consul:
    image: consul:1.0.7
    environment:
      CONSUL_BIND_INTERFACE: eth0
    ports:
      - 8500:8500
    labels:
      - "terraform-api.role=consul"
    restart: "always"

  webapp:
    image: gregoryguillou/terraform-stacks:v0.1.3-app
    ports:
      - 8000:8000
    restart: "always"
    depends_on:
      - consul

  couchbase:
    image: couchbase:community-5.0.1
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    labels:
      - "terraform-api.role=couchbase-server"
    restart: "always"

  couchbase-setup:
    image: couchbase:community-5.0.1
    volumes:
      - $PWD/couchbase-setup.sh:/script/couchbase-setup.sh
    depends_on:
      - couchbase
    command: ['/script/couchbase-setup.sh']
    restart: "no"

  redis:
    image: redis:3.2
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes' ]
    labels:
      - "terraform-api.role=redis-server"
    restart: "always"
