version: '3.2'

services:
  terraform-deck:
    image: "gregoryguillou/terraform-deck:${VERSION:-v0.1.3}"
    ports:
      - 10010:10010
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - $PWD/../../api/config/settings-template.yaml:/app/config/settings.yaml
    depends_on:
      - consul
      - couchbase
    command:
      - npm
      - "${DECK_MODE:-start}"
    environment:
      SECRETORKEY: secret
      CONSUL_IP: "172.28.0.1"

  terraform-demo:
    image: "gregoryguillou/terraform-deck:${VERSION:-v0.1.3}-demo"
    depends_on:
      - consul
    environment:
      CONSUL_IP: consul
    command: ["sleep", "10"]
    entrypoint: ["/bin/bash"]
    restart: "no"

  consul:
    image: consul:1.0.6
    environment:
      CONSUL_BIND_INTERFACE: eth0
    ports:
      - 8500:8500
    labels:
      - "deck.role=consul"
    restart: "always"

  couchbase:
    image: couchbase:community-5.0.1
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    restart: "always"

  couchbase-setup:
    image: couchbase:community-5.0.1
    volumes:
     - $PWD/couchbase-setup.sh:/script/couchbase-setup.sh
    depends_on:
      - couchbase
    command: ['/script/couchbase-setup.sh']
    restart: "no"
