swagger: "2.0"
info:
  version: "0.0.1"
  title: Terraform Lineup
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /monitor/docker:
    x-swagger-router-controller: docker
    get:
      tags:
        - admin
      description: Returns 'Unauthorized Access' to the caller
      operationId: docker_list
      responses:
        "200":
          description: Success
          schema:
            type: array
            items: 
              $ref: "#/definitions/Container"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /login:
    x-swagger-router-controller: login
    get:
      tags:
        - auth
      description: Returns the JWT token to the caller
      operationId: login_token
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/JwtResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /unauthorized:
    # binds a127 app logic to a route
    x-swagger-router-controller: login
    get:
      tags:
        - auth
      description: Returns 'Unauthorized Access' to the caller
      operationId: login_unauthorized
      responses:
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /user:
    x-swagger-router-controller: login
    get:
      tags:
        - auth
      description: Return the username of the caller based on the JWT token
      operationId: login_user
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UserResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Container:
    required:
      - identifier
    properties:
      identifier:
        type: string
      name:
        type: string
      image:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  JwtResponse:
    required:
      - token
    properties:
      message:
        type: string
      token:
        type: string
  UserResponse:
    required:
      - username
    properties:
      username:
        type: string
