swagger: "2.0"
info:
  version: "0.1.7"
  title: Terraform-api
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /events/{event}:
    x-swagger-router-controller: events
    get:
      tags:
        - main
      description: Returns the description of a given event
      operationId: event_describe
      parameters:
        - in: path
          name: event
          type: string
          required: true
          description: Event to get.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Event"
        "404":
          description: Event Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /events/{event}/logs:
    x-swagger-router-controller: events
    get:
      tags:
        - main
      description: Returns logs of a given event
      operationId: event_logs
      parameters:
        - in: path
          name: event
          type: string
          required: true
          description: Event to get.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Logs"
        "404":
          description: Event Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /login:
    x-swagger-router-controller: login
    get:
      tags:
        - auth
      description: Returns the JWT token to the caller
      operationId: login_token
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/JwtResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /projects:
    x-swagger-router-controller: projects
    get:
      tags:
        - main
      description: Return a list of projects managed by the API
      operationId: projects_list
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Projects"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /projects/{project}:
    x-swagger-router-controller: projects
    get:
      tags:
        - main
      description: Returns the description of a given project
      operationId: project_describe
      parameters:
        - in: path
          name: project
          type: string
          required: true
          description: Project to get.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ProjectDescription"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags:
        - main
      description: Send an action to a given project
      operationId: project_action
      parameters:
        - in: path
          name: project
          type: string
          required: true
          description: Project to apply the action too.
        - in: body
          name: action
          description: The action to execute
          required: true
          schema:
            type: object
            required:
              - action
            properties:
              action:
                type: string
                enum: ["reserve", "release", "refresh"]
      responses:
        "201":
          description: Created
  /projects/{project}/branches:
    x-swagger-router-controller: projects
    get:
      tags:
        - main
      description: Returns a list of branches associated with a given project
      operationId: project_branches
      parameters:
        - in: path
          name: project
          type: string
          required: true
          description: Project to get events from.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Branches"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /projects/{project}/tags:
    x-swagger-router-controller: projects
    get:
      tags:
        - main
      description: Returns a list of tags associated with a given project
      operationId: project_tags
      parameters:
        - in: path
          name: project
          type: string
          required: true
          description: Project to get tags from.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Tags"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /projects/{project}/workspaces:
    x-swagger-router-controller: projects
    get:
      tags:
        - main
      description: Returns a list of tags associated with a given project
      operationId: project_workspaces
      parameters:
        - in: path
          name: project
          type: string
          required: true
          description: Project to get workspaces from.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Workspaces"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /projects/{project}/workspaces/{workspace}:
    x-swagger-router-controller: workspaces
    get:
      tags:
        - main
      description: Returns the description of a given project/workspace
      operationId: workspace_describe
      parameters:
        - in: path
          name: project
          type: string
          required: true
          description: Project to get the workspace from.
        - in: path
          name: workspace
          type: string
          required: true
          description: Workspace to get
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Workspace"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags:
        - main
      description: Send an action to a given workspace
      operationId: workspace_action
      parameters:
        - in: path
          name: project
          type: string
          required: true
          description: Project to get the workspace from.
        - in: path
          name: workspace
          type: string
          required: true
          description: Workspace to get
        - in: body
          name: action
          description: The action to execute
          required: true
          schema:
            type: object
            required:
              - action
            properties:
              action:
                type: string
                enum: ["apply", "check", "clean", "destroy", "reference"]
              ref:
                type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: "#/definitions/EventDescription"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /projects/{project}/workspaces/{workspace}/status:
    x-swagger-router-controller: workspaces
    get:
      tags:
        - main
      description: Returns the description of a given project/workspace
      operationId: workspace_status
      parameters:
        - in: path
          name: project
          type: string
          required: true
          description: Project to get the workspace from.
        - in: path
          name: workspace
          type: string
          required: true
          description: Workspace to get
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/StatusResponse"
        "404":
          description: Success
          schema:
            $ref: "#/definitions/StatusResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /projects/{project}/workspaces/{workspace}/version:
    x-swagger-router-controller: workspaces
    get:
      tags:
        - main
      description: Returns the current version of a given project/workspace
      operationId: workspace_version
      parameters:
        - in: path
          name: project
          type: string
          required: true
          description: Project to get the workspace from.
        - in: path
          name: workspace
          type: string
          required: true
          description: Workspace to get
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/VersionResponse"
        "404":
          description: Success
          schema:
            $ref: "#/definitions/VersionResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /sessions:
    x-swagger-router-controller: sessions
    get:
      tags:
        - main
      description: Return a the list of sessions currently in use
      operationId: sessions_list
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Sessions"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /sessions/{session}:
    x-swagger-router-controller: sessions
    get:
      tags:
        - main
      description: Returns the project/workspace associated with a given sessions
      operationId: session_describe
      parameters:
        - in: path
          name: session
          type: string
          required: true
          description: Session to get.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SessionDescription"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /user:
    x-swagger-router-controller: login
    get:
      tags:
        - auth
      description: Return the username of the caller based on the JWT token
      operationId: login_user
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /version:
    x-swagger-router-controller: version
    get:
      tags:
        - auth
      description: Return the API version
      operationId: version
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Version"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /status:
    x-swagger-router-controller: version
    get:
      tags:
        - auth
      description: Return a 200 to help the loadbalancer check the status
      operationId: status
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Branches:
    required:
      - branches
    properties:
      branches:
        type: array
        items:
          type: object
          required:
            - name
          properties:
            name:
              type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  Event:
    required:
      - action
      - creation
      - project
    properties:
      action:
        type: string
      creation:
        type: integer
      project:
        type: string
      ref:
        type: string
      status:
        type: string
      workspace:
        type: string
  EventDescription:
    required:
      - event
    properties:
      event:
        type: string
  JwtResponse:
    required:
      - token
    properties:
      message:
        type: string
      token:
        type: string
  Logs:
    required:
      - logs
    properties:
      logs:
        type: array
        items:
          type: object
          required:
            - line
            - text
          properties:
            line:
              type: integer
            text:
              type: string
      type:
        type: string
  Projects:
    required:
      - projects
    properties:
      projects:
        type: array
        items:
          type: object
          required:
            - name
            - type
          properties:
            name:
              type: string
            description:
              type: string
            type:
              type: string
  ProjectDescription:
    required:
      - name
      - type
    properties:
      name:
        type: string
      description:
        type: string
      type:
        type: string
      workspaces:
        type: array
        items:
          type: object
          required:
            - name
          properties:
            name:
              type: string
            status:
              type: string
  Sessions:
    required:
      - sessions
    properties:
      sessions:
        type: array
        items:
          type: object
          required:
            - id
          properties:
            id:
              type: string
  SessionDescription:
    required:
      - id
      - project
      - workspace
    properties:
      id:
        type: string
      project:
        type: string
      workspace:
        type: string
  StatusResponse:
    required:
      - quickCheck
      - state
    properties:
      quickCheck:
        type: string
      ref:
        type: string
      state:
        type: string
      lastChecked:
        type: object
        properties:
          date:
            type: integer
          state:
            type: string
          ref:
            type: string
  Tags:
    required:
      - tags
    properties:
      tags:
        type: array
        items:
          type: object
          required:
            - name
          properties:
            name:
              type: string
  User:
    required:
      - username
    properties:
      username:
        type: string
  Version:
    required:
      - version
    properties:
      version:
        type: string
  VersionResponse:
    required:
      - appVersion
      - state
    properties:
      appVersion:
        type: string
      ref:
        type: string
      state:
        type: string
      lastChecked:
        type: object
        properties:
          date:
            type: integer
          state:
            type: string
          ref:
            type: string
  Workspace:
    required:
      - project
      - workspace
      - state
    properties:
      creation:
        type: integer
      lastEvents:
        type: array
        items:
          type: string
      lastChecked:
        type: object
        properties:
          date:
            type: integer
          state:
            type: string
          ref:
            type: string
      project:
        type: string
      ref:
        type: string
      request:
        type: object
        properties:
          date:
            type: integer
          action:
            type: string
          ref:
            type: string
          event:
            type: string
      session:
        type: string
      state:
        type: string
      type:
        type: string
      workspace:
        type: string
  Workspaces:
    required:
      - workspaces
    properties:
      workspaces:
        type: array
        items:
          type: object
          required:
            - name
          properties:
            name:
              type: string
