version: '3.2'

services:
  lineup-service:
    image: lineup-service:alpha1
    ports:
      - 10010:10010
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - consul
    environment:
      SECRETORKEY: secret
      CONSUL_IP: "172.28.0.1"

  consul:
    image: consul:1.0.6
    environment:
      CONSUL_BIND_INTERFACE: eth0
    ports:
      - 8500:8500
    labels:
      - "lineup.role=consul"
    restart: "always"

  couchbase:
    image: couchbase:5.1.0
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    restart: "always"

  couchbase-setup:
    image: couchbase:5.1.0
    volumes:
     - $PWD/couchbase-setup.sh:/script/couchbase-setup.sh
    depends_on:
      - couchbase
    command: ['/script/couchbase-setup.sh']
    restart: "no"
