// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/gregoryguillou/terraform-api/server/models"
)

// ProjectsListOKCode is the HTTP code returned for type ProjectsListOK
const ProjectsListOKCode int = 200

/*ProjectsListOK Success

swagger:response projectsListOK
*/
type ProjectsListOK struct {

	/*
	  In: Body
	*/
	Payload *models.Projects `json:"body,omitempty"`
}

// NewProjectsListOK creates ProjectsListOK with default headers values
func NewProjectsListOK() *ProjectsListOK {

	return &ProjectsListOK{}
}

// WithPayload adds the payload to the projects list o k response
func (o *ProjectsListOK) WithPayload(payload *models.Projects) *ProjectsListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the projects list o k response
func (o *ProjectsListOK) SetPayload(payload *models.Projects) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProjectsListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ProjectsListDefault Error

swagger:response projectsListDefault
*/
type ProjectsListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewProjectsListDefault creates ProjectsListDefault with default headers values
func NewProjectsListDefault(code int) *ProjectsListDefault {
	if code <= 0 {
		code = 500
	}

	return &ProjectsListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the projects list default response
func (o *ProjectsListDefault) WithStatusCode(code int) *ProjectsListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the projects list default response
func (o *ProjectsListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the projects list default response
func (o *ProjectsListDefault) WithPayload(payload *models.Error) *ProjectsListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the projects list default response
func (o *ProjectsListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProjectsListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
