// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ProjectsListHandlerFunc turns a function with the right signature into a projects list handler
type ProjectsListHandlerFunc func(ProjectsListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ProjectsListHandlerFunc) Handle(params ProjectsListParams) middleware.Responder {
	return fn(params)
}

// ProjectsListHandler interface for that can handle valid projects list params
type ProjectsListHandler interface {
	Handle(ProjectsListParams) middleware.Responder
}

// NewProjectsList creates a new http.Handler for the projects list operation
func NewProjectsList(ctx *middleware.Context, handler ProjectsListHandler) *ProjectsList {
	return &ProjectsList{Context: ctx, Handler: handler}
}

/*ProjectsList swagger:route GET /projects app projectsList

Return a list of projects managed by the API

*/
type ProjectsList struct {
	Context *middleware.Context
	Handler ProjectsListHandler
}

func (o *ProjectsList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewProjectsListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
