// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Terraform API v2.x
A rewrite of the Terraform API with Go


    Schemes:
      http
      https
    Host: localhost
    BasePath: /
    Version: 2.0.0

    Consumes:
    - application/com.resetlogs.terraform-api.v2+json

    Produces:
    - application/com.resetlogs.terraform-api.v2+json

swagger:meta
*/
package restapi
