// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/com.resetlogs.terraform-api.v2+json"
  ],
  "produces": [
    "application/com.resetlogs.terraform-api.v2+json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A rewrite of the Terraform API with Go",
    "title": "Terraform API v2.x",
    "version": "2.0.0"
  },
  "paths": {
    "/projects": {
      "x-swagger-router-controller": "projects",
      "get": {
        "description": "Return a list of projects managed by the API",
        "tags": [
          "app"
        ],
        "operationId": "projects_list",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Projects"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Projects": {
      "required": [
        "projects"
      ],
      "properties": {
        "projects": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "name",
              "type"
            ],
            "properties": {
              "description": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "type": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/com.resetlogs.terraform-api.v2+json"
  ],
  "produces": [
    "application/com.resetlogs.terraform-api.v2+json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A rewrite of the Terraform API with Go",
    "title": "Terraform API v2.x",
    "version": "2.0.0"
  },
  "paths": {
    "/projects": {
      "x-swagger-router-controller": "projects",
      "get": {
        "description": "Return a list of projects managed by the API",
        "tags": [
          "app"
        ],
        "operationId": "projects_list",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Projects"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Projects": {
      "required": [
        "projects"
      ],
      "properties": {
        "projects": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/projectsProjectsItems"
          }
        }
      }
    },
    "projectsProjectsItems": {
      "type": "object",
      "required": [
        "name",
        "type"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "x-go-gen-location": "models"
    }
  }
}`))
}
