bots:
  - name: donatello
    type: slack
    prefix: staging
    apiurl: http://terraform-api:10010
    apikey: notsosecretadminkey
    project: demonstration
    workspace: staging
    slack:
      userbot_token: xxx
      app_token: yyy



  