api:
  clone-directory: /tmp
couchbase:
  url: couchbase:8091
  username: admin
  password: couchbase
  data_bucket: data
  log_bucket: logs
  'bucket-password': couchbase
docker:
  socketPath: '/var/run/docker.sock'
jwt:
  secretOrKey: secret
pool:
  type: docker
projects:
  - type: terraform
    name: demonstration
    description: A demonstration project that relies on Terraform/Consul
    docker-image: "gregoryguillou/terraform-api:latest-runtime"
    git:
      # the repository must be an https repository and it should not be
      # prefixed down here, i.e. use github.com/...
      repository: github.com/gregoryguillou/terraform-stacks.git
      branch: master
      username: username
      password: "password"
      # the directory must be relative, i.e. not star with / and be '.'
      # if that's the root directory of the project
      directory: demo
    workspaces:
      - staging
      - qa
      - test
      - development
    lifecycle:
      cwd: projects/demonstration
      getenv:
        - ./getenv.sh {{terraform-api.WORKSPACE}}
      setenv:
        - CONSUL_IP={{env.CONSUL}}
      status:
        - ./status.sh -w {{terraform-api.WORKSPACE}}
      version:
        - ./version.sh -w {{terraform-api.WORKSPACE}}
users:
  - username: 'gregory'
    apikey: 'notsosecretadminkey'
    role: administrator
  - username: 'kilian'
    apikey: 'nososecretuserkey'
    role: user
