api:
  clone-directory: /tmp
couchbase:
  url: couchbase:8091
  username: admin
  password: couchbase
  data_bucket: data
  log_bucket: logs
  'bucket-password': couchbase
docker:
  socketPath: '/var/run/docker.sock'
jwt:
  secretOrKey: secret
pool:
  type: docker
projects:
  - type: terraform
    name: demonstration
    description: A demonstration project that relies on Terraform/Consul
    docker-image: "deck-terraform:v0.1.3-demo"
    git:
      repository: github.com/gregoryguillou/terraform-deck.git
      branch: master
      username: username
      password: "password"
      directory: /demo/terraform/starter
    workspaces:
      - staging
      - qa
      - test
      - development
    lifecycle:
      cwd: projects/demonstration
      before-start:
        - echo "Ready to kick-off a creation container..."
      pre-start:
        - echo "Ready to begin..."
      on-success:
        - echo "The environment was successful"
      on-failure:
        - echo "You've screwed up!"
      post-finish:
        - echo "Ready to begin..."
      status:
        - ./status.sh -w {{deck.WORKSPACE}}
    # Define the environment variables that should be used when running the project
    # management commands (i.e. apply, destroy, list and check)
    setenv:
      - CONSUL_IP={{env.CONSUL_IP}}
      - AWS_PROFILE={{env.DEMONSTRATION__AWS_PROFILE}}
users:
  - username: 'gregory'
    apikey: 'notsosecretadminkey'
    role: administrator
  - username: 'kilian'
    apikey: 'nososecretuserkey'
    role: user
